import { describe, it, expect, beforeEach } from 'vitest'
import { smartMergeIndexCss } from '../css-smart-merge'
import { LightningFSAdapter } from '../../fs/LightningFSAdapter'
import { ShellExecutor } from '../executor'
import { registerAllCommands } from '../commands'

// Minimal but realistic generated theme CSS
const GENERATED_THEME = `/* Generated by theme command — use theme modify to adjust */

:root {
  --font-sans: "Inter", sans-serif;
  --radius: 0.5rem;
  --background: oklch(0.98 0.005 90);
  --foreground: oklch(0.15 0.01 90);
  --card: oklch(0.97 0.005 90);
  --card-foreground: oklch(0.15 0.01 90);
  --primary: oklch(0.55 0.15 250);
  --primary-foreground: oklch(0.98 0.005 250);
  --secondary: oklch(0.90 0.03 250);
  --secondary-foreground: oklch(0.20 0.02 250);
  --muted: oklch(0.92 0.01 90);
  --muted-foreground: oklch(0.45 0.02 90);
  --accent: oklch(0.85 0.05 250);
  --accent-foreground: oklch(0.20 0.02 250);
  --border: oklch(0.88 0.01 90);
  --ring: oklch(0.55 0.15 250);
  --chart-1: oklch(0.60 0.20 30);
}

.dark {
  --background: oklch(0.15 0.005 90);
  --foreground: oklch(0.95 0.005 90);
  --card: oklch(0.18 0.005 90);
  --card-foreground: oklch(0.95 0.005 90);
  --primary: oklch(0.65 0.15 250);
  --primary-foreground: oklch(0.10 0.005 250);
}

* {
  box-sizing: border-box;
  border-color: var(--border);
}

body {
  margin: 0;
  background-color: var(--background);
  color: var(--foreground);
}
`

describe('smartMergeIndexCss', () => {
  // Test 1: No generator marker → passthrough
  it('passes through when no generator marker exists', () => {
    const existing = ':root { --color: red; }\n'
    const incoming = ':root { --color: blue; }\n.custom { display: flex; }\n'

    const result = smartMergeIndexCss(existing, incoming)

    expect(result.content).toBe(incoming)
    expect(result.report).toBe('')
    expect(result.colorUpdates).toEqual({})
  })

  // Test 2: Custom CSS only (no :root/:dark) → theme preserved, custom appended
  it('preserves theme and appends custom CSS when incoming has no overrides', () => {
    const incoming = `.hero { font-size: 3rem; }
.card { padding: 1.5rem; }`

    const result = smartMergeIndexCss(GENERATED_THEME, incoming)

    // Theme zone preserved
    expect(result.content).toContain('/* Generated by theme command')
    expect(result.content).toContain('--primary: oklch(0.55 0.15 250)')
    // Custom CSS appended
    expect(result.content).toContain('.hero { font-size: 3rem; }')
    expect(result.content).toContain('.card { padding: 1.5rem; }')
    expect(result.report).toContain('preserved theme')
  })

  // Test 3: Theme vars + custom CSS → valid overrides applied, custom appended
  it('applies valid overrides and appends custom CSS', () => {
    // border has no contrast pair → always accepted
    const incoming = `:root {
  --border: oklch(0.80 0.02 90);
}

.hero { font-size: 3rem; }`

    const result = smartMergeIndexCss(GENERATED_THEME, incoming)

    expect(result.content).toContain('--border: oklch(0.80 0.02 90)')
    expect(result.content).toContain('.hero { font-size: 3rem; }')
    expect(result.report).toContain('applied 1 overrides')
  })

  // Test 4: Color override passes contrast (≥4.5) → accepted
  it('accepts color override when contrast ratio ≥ 4.5', () => {
    // Override primary to a dark color. Against primary-foreground (L=0.98) → high contrast
    const incoming = `:root {
  --primary: oklch(0.40 0.15 200);
}`

    const result = smartMergeIndexCss(GENERATED_THEME, incoming)

    expect(result.content).toContain('--primary: oklch(0.40 0.15 200)')
    expect(result.report).toContain('applied 1 overrides')
    expect(result.colorUpdates).toHaveProperty('primary')
  })

  // Test 5: Color override fails contrast (<4.5) → REJECTED, existing kept
  it('rejects color override when contrast ratio < 4.5 and keeps existing', () => {
    // Override primary to near-white — against primary-foreground (L=0.98) → very low contrast
    const incoming = `:root {
  --primary: oklch(0.92 0.02 250);
}`

    const result = smartMergeIndexCss(GENERATED_THEME, incoming)

    // Original primary preserved
    expect(result.content).toContain('--primary: oklch(0.55 0.15 250)')
    // Should NOT contain the override
    expect(result.content).not.toContain('--primary: oklch(0.92 0.02 250)')
    // Report shows skip
    expect(result.report).toContain('Skipped')
    expect(result.report).toContain('contrast')
    // No color updates
    expect(result.colorUpdates).not.toHaveProperty('primary')
  })

  // Test 6: Non-color override → always accepted
  it('always accepts non-color overrides', () => {
    const incoming = `:root {
  --font-sans: "Plus Jakarta Sans", sans-serif;
  --radius: 0.75rem;
}`

    const result = smartMergeIndexCss(GENERATED_THEME, incoming)

    expect(result.content).toContain('--font-sans: "Plus Jakarta Sans", sans-serif')
    expect(result.content).toContain('--radius: 0.75rem')
    expect(result.report).toContain('applied 2 overrides')
  })

  // Test 7: @fonts comment extracted and placed at top
  it('extracts @fonts comment and places at top of merged file', () => {
    const incoming = `/* @fonts: Plus Jakarta Sans:wght@400;500;700 */

:root {
  --font-sans: "Plus Jakarta Sans", sans-serif;
}`

    const result = smartMergeIndexCss(GENERATED_THEME, incoming)

    // @fonts comment should be at the very start
    expect(result.content.trimStart().startsWith('/* @fonts:')).toBe(true)
    // Font override applied
    expect(result.content).toContain('--font-sans: "Plus Jakarta Sans"')
    expect(result.fontsComment).toContain('@fonts:')
  })

  // Test 8: Both fg and bg overridden → contrast checked between TWO NEW values
  it('checks contrast between two new values when both fg and bg are overridden', () => {
    // Both primary and primary-foreground overridden to similar lightness → low contrast
    const incoming = `:root {
  --primary: oklch(0.60 0.10 200);
  --primary-foreground: oklch(0.65 0.03 200);
}`

    const result = smartMergeIndexCss(GENERATED_THEME, incoming)

    // Both should be rejected (low contrast between them)
    expect(result.report).toContain('Skipped')
    // Original values preserved
    expect(result.content).toContain('--primary: oklch(0.55 0.15 250)')
    expect(result.content).toContain('--primary-foreground: oklch(0.98 0.005 250)')
  })

  // Test 9: Dark mode overrides applied independently from light
  it('applies dark mode overrides independently', () => {
    // Override dark background to something different but valid contrast
    const incoming = `.dark {
  --background: oklch(0.12 0.01 200);
  --foreground: oklch(0.93 0.005 200);
}`

    const result = smartMergeIndexCss(GENERATED_THEME, incoming)

    // Dark overrides applied
    expect(result.content).toContain('--background: oklch(0.12 0.01 200)')
    expect(result.content).toContain('--foreground: oklch(0.93 0.005 200)')
    // Light mode untouched
    expect(result.content).toMatch(/^:root \{[^}]*--background: oklch\(0\.98 0\.005 90\)/m)
    expect(result.report).toContain('applied 2 overrides')
  })

  // Test 10: Append mode (>>) does NOT trigger smart merge — integration test
  it('does not trigger smart merge for append mode', async () => {
    const fs = new LightningFSAdapter('test-smart-merge-' + Date.now(), { wipe: true })
    await fs.mkdir('/project/src', { recursive: true })
    await fs.writeFile('/project/src/index.css', GENERATED_THEME)

    const executor = new ShellExecutor(fs)
    registerAllCommands(executor)

    // Append mode — should NOT smart merge
    const result = await executor.execute('echo ".extra { color: red; }" >> src/index.css', '/project')

    expect(result.exitCode).toBe(0)
    const content = await fs.readFile('/project/src/index.css', { encoding: 'utf8' }) as string
    // Should be simple append — original + appended text
    expect(content).toContain('.extra { color: red; }')
    expect(content).toContain('/* Generated by theme command')
  })

  // Test 11: Existing custom CSS preserved, not duplicated when new custom added
  it('preserves existing custom CSS and appends new without duplication', () => {
    const existingWithCustom = GENERATED_THEME + '\n.existing-custom { display: grid; }\n'

    const incoming = `.new-custom { gap: 1rem; }`

    const result = smartMergeIndexCss(existingWithCustom, incoming)

    // Both custom blocks present
    expect(result.content).toContain('.existing-custom { display: grid; }')
    expect(result.content).toContain('.new-custom { gap: 1rem; }')
    // No duplication
    const existingCount = (result.content.match(/\.existing-custom/g) || []).length
    expect(existingCount).toBe(1)
  })

  // Bonus: incoming starts with theme marker → full passthrough (theme --apply rewrite)
  it('passes through when incoming starts with theme marker', () => {
    const newTheme = `/* Generated by theme command — use theme modify to adjust */
:root { --primary: oklch(0.50 0.20 300); }`

    const result = smartMergeIndexCss(GENERATED_THEME, newTheme)

    expect(result.content).toBe(newTheme)
    expect(result.report).toBe('')
  })
})
