/**
 * AUTO-GENERATED — DO NOT EDIT
 *
 * Runtime arrays for plan validation.
 * Generated by: pnpm --filter @wiggum/planning generate-types
 */

/** 12 personality moods */
export const MOOD_NAMES = [
  'minimal', 'premium', 'playful', 'industrial',
  'organic', 'editorial', 'fashion-editorial', 'brutalist',
  'zen', 'corporate', 'retro', 'luxury',
] as const

/** 12 curated presets */
export const PRESET_NAMES = [
  'northern-lights', 'cyberpunk', 'doom-64', 'retro-arcade',
  'soft-pop', 'tangerine', 'mono', 'elegant-luxury',
  'bubblegum', 'mocha-mousse', 'caffeine', 'catppuccin',
] as const

/** 11 geometry patterns */
export const PATTERN_NAMES = [
  'monochromatic', 'analogous', 'complementary', 'splitComplementary',
  'triadic', 'tetradic', 'goldenRatio', 'flowerOfLife',
  'fibonacci', 'vesicaPiscis', 'seedOfLife',
] as const

/** 32 curated fonts */
export const FONT_NAMES = [
  'Inter', 'Plus Jakarta Sans', 'Outfit', 'Poppins',
  'Manrope', 'Sora', 'Space Grotesk', 'DM Sans',
  'Nunito', 'Rubik', 'Lexend', 'Geist',
  'IBM Plex Sans', 'Work Sans', 'Montserrat', 'Source Serif 4',
  'Merriweather', 'Lora', 'Libre Baskerville', 'Crimson Pro',
  'Roboto Slab', 'Zilla Slab', 'Oxanium', 'Orbitron',
  'Righteous', 'Comfortaa', 'Josefin Sans', 'JetBrains Mono',
  'Geist Mono', 'Fira Code', 'IBM Plex Mono', 'Source Code Pro',
] as const

/** 5 shadow profiles */
export const SHADOW_PROFILES = [
  'none', 'subtle', 'moderate', 'dramatic',
  'harsh',
] as const

/** 5 radius stops */
export const RADIUS_STOPS = [
  'none', 'subtle', 'moderate', 'rounded',
  'pill',
] as const

/** 52 gumdrops */
export const GUMDROP_NAMES = [
  'activity-feed', 'ai-prompt', 'api-auth', 'api-crud', 'api-realtime',
  'api-search', 'api-upload', 'api-webhook', 'article-layout', 'auth-login',
  'blog-grid', 'calendar-view', 'changelog', 'chat-messaging', 'color-picker',
  'command-palette', 'contact', 'cta', 'data-table', 'dialog-modal',
  'documentation', 'drag-drop', 'empty-state', 'faq', 'features',
  'file-browser', 'file-upload', 'footer', 'form-layout', 'gallery',
  'grid-list', 'hero', 'kanban-board', 'keyboard-shortcuts', 'motion-patterns',
  'multi-step-wizard', 'newsletter', 'notification-feed', 'onboarding', 'portfolio',
  'pricing', 'profile-page', 'rich-text-editor', 'scroll-animation', 'search-results',
  'settings-panel', 'sidebar-nav', 'social-proof', 'stats-dashboard', 'team',
  'testimonials', 'timeline',
] as const

/** 53 stack components */
export const STACK_COMPONENTS = [
  'Accordion', 'Alert', 'AlertDialog', 'AspectRatio', 'Avatar',
  'Badge', 'Breadcrumb', 'Button', 'ButtonGroup', 'Calendar',
  'Card', 'Carousel', 'Chart', 'Checkbox', 'Collapsible',
  'Command', 'ContextMenu', 'Dialog', 'Drawer', 'DropdownMenu',
  'Empty', 'Field', 'Form', 'HoverCard', 'Input',
  'InputGroup', 'InputOtp', 'Item', 'Kbd', 'Label',
  'Menubar', 'NavigationMenu', 'Pagination', 'Popover', 'Progress',
  'RadioGroup', 'Resizable', 'ScrollArea', 'Select', 'Separator',
  'Sheet', 'Sidebar', 'Skeleton', 'Slider', 'Sonner',
  'Spinner', 'Switch', 'Table', 'Tabs', 'Textarea',
  'Toggle', 'ToggleGroup', 'Tooltip',
] as const
