/**
 * AUTO-GENERATED — DO NOT EDIT
 *
 * Generated by: pnpm --filter @wiggum/planning generate-types
 * Sources: personality.ts, personalities.ts, presets.ts, patterns.ts,
 *          gumdrops/ *.md (all domains), stack/src/components/ui/index.ts
 */

/** 12 personality moods from personalities.ts */
export type MoodName =
  | 'minimal' | 'premium' | 'playful' | 'industrial'
  | 'organic' | 'editorial' | 'fashion-editorial' | 'brutalist'
  | 'zen' | 'corporate' | 'retro' | 'luxury'

/** 12 curated presets from presets.ts */
export type PresetName =
  | 'northern-lights' | 'cyberpunk' | 'doom-64' | 'retro-arcade'
  | 'soft-pop' | 'tangerine' | 'mono' | 'elegant-luxury'
  | 'bubblegum' | 'mocha-mousse' | 'caffeine' | 'catppuccin'

/** 11 geometry patterns from patterns.ts */
export type PatternName =
  | 'monochromatic' | 'analogous' | 'complementary' | 'splitComplementary'
  | 'triadic' | 'tetradic' | 'goldenRatio' | 'flowerOfLife'
  | 'fibonacci' | 'vesicaPiscis' | 'seedOfLife'

/** 32 curated fonts from FONT_REGISTRY */
export type FontName =
  | 'Inter' | 'Plus Jakarta Sans' | 'Outfit' | 'Poppins'
  | 'Manrope' | 'Sora' | 'Space Grotesk' | 'DM Sans'
  | 'Nunito' | 'Rubik' | 'Lexend' | 'Geist'
  | 'IBM Plex Sans' | 'Work Sans' | 'Montserrat' | 'Source Serif 4'
  | 'Merriweather' | 'Lora' | 'Libre Baskerville' | 'Crimson Pro'
  | 'Roboto Slab' | 'Zilla Slab' | 'Oxanium' | 'Orbitron'
  | 'Righteous' | 'Comfortaa' | 'Josefin Sans' | 'JetBrains Mono'
  | 'Geist Mono' | 'Fira Code' | 'IBM Plex Mono' | 'Source Code Pro'

/** 5 shadow profiles */
export type ShadowProfile =
  | 'none' | 'subtle' | 'moderate' | 'dramatic'
  | 'harsh'

/** 5 radius stops */
export type RadiusStop =
  | 'none' | 'subtle' | 'moderate' | 'rounded'
  | 'pill'

/** 52 gumdrops from skills/gumdrops + API forward-declarations */
export type GumDropName =
  | 'activity-feed' | 'ai-prompt' | 'api-auth' | 'api-crud' | 'api-realtime'
  | 'api-search' | 'api-upload' | 'api-webhook' | 'article-layout' | 'auth-login'
  | 'blog-grid' | 'calendar-view' | 'changelog' | 'chat-messaging' | 'color-picker'
  | 'command-palette' | 'contact' | 'cta' | 'data-table' | 'dialog-modal'
  | 'documentation' | 'drag-drop' | 'empty-state' | 'faq' | 'features'
  | 'file-browser' | 'file-upload' | 'footer' | 'form-layout' | 'gallery'
  | 'grid-list' | 'hero' | 'kanban-board' | 'keyboard-shortcuts' | 'motion-patterns'
  | 'multi-step-wizard' | 'newsletter' | 'notification-feed' | 'onboarding' | 'portfolio'
  | 'pricing' | 'profile-page' | 'rich-text-editor' | 'scroll-animation' | 'search-results'
  | 'settings-panel' | 'sidebar-nav' | 'social-proof' | 'stats-dashboard' | 'team'
  | 'testimonials' | 'timeline'
  | (string & {})

/** 53 components from @wiggum/stack */
export type StackComponent =
  | 'Accordion' | 'Alert' | 'AlertDialog' | 'AspectRatio' | 'Avatar'
  | 'Badge' | 'Breadcrumb' | 'Button' | 'ButtonGroup' | 'Calendar'
  | 'Card' | 'Carousel' | 'Chart' | 'Checkbox' | 'Collapsible'
  | 'Command' | 'ContextMenu' | 'Dialog' | 'Drawer' | 'DropdownMenu'
  | 'Empty' | 'Field' | 'Form' | 'HoverCard' | 'Input'
  | 'InputGroup' | 'InputOtp' | 'Item' | 'Kbd' | 'Label'
  | 'Menubar' | 'NavigationMenu' | 'Pagination' | 'Popover' | 'Progress'
  | 'RadioGroup' | 'Resizable' | 'ScrollArea' | 'Select' | 'Separator'
  | 'Sheet' | 'Sidebar' | 'Skeleton' | 'Slider' | 'Sonner'
  | 'Spinner' | 'Switch' | 'Table' | 'Tabs' | 'Textarea'
  | 'Toggle' | 'ToggleGroup' | 'Tooltip'
  | (string & {})
